### ISSUE TITLE
filebeat.yml permissions

### ISSUE THREAD

**Issue by stickperson** [primait/docker-filebeat#13]
I'm seeing the following when running this with my own `filebeat.yml` file:
`Exiting: error loading config file: config file ("filebeat.yml") must be owned by the beat user (uid=0) or root`

This works fine when I'm running docker for mac, but I get the error on linux.

**Comment by andreausu** [comment]
Hi,

that's actually a new requirement as of filebeat 5.3.0: https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-5.3.0.html
You should chown your `filebeat.yml` to root and `chmod 600` on the host before mounting it in the filebeat container.

**Comment by stickperson** [comment]
Ah cool, thanks for the info

**Comment by bvarsur** [comment]
I'm facing same problem .i did it above solution but it won't happen in my case
