### ISSUE TITLE
Possible to offer a Filebeat alpha docker image?

### ISSUE THREAD

**Issue by LoungeFlyZ** [primait/docker-filebeat#3]
It would be great if it were possible to offer a docker image based on the alpha/beta releases of Filebeat for testing/playing with.  vs. forking.

thanks for this image!

**Comment by andreausu** [comment]
Great suggestion!
It's done, you can already see the new tags on Docker Hub :)

**Comment by LoungeFlyZ** [comment]
Great! thanks!

PS: if you want to go full hardcore mode there is a nightly drop available too:
https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/

We are currently using that due to some bug fixes in it.
