### ISSUE TITLE
Are new containers added without a restart?

### ISSUE THREAD

**Issue by noseglid** [primait/docker-filebeat#6]
We're looking to switch from [digital-wonderland/docker-logstash-forwarder](https://github.com/digital-wonderland/docker-logstash-forwarder). It has a nice feature that it listens to docker events and automatically refreshes the files it's looking at (which is mounted from `/var/lib/docker` from the host) when a container is created/deleted.

Is this supported in `docker-filebeat` too?

**Comment by andreausu** [comment]
Hi, I think it's better to keep this docker image as is in order not to clutter it for people who don't need that kind of functionality which could be built in a separate docker image that uses this one as the base one by anyone who's willing to do so :)
